// <auto-generated />
namespace ViverBemADM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Change_To_Date : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_To_Date));
        
        string IMigrationMetadata.Id
        {
            get { return "201602240047541_Change_To_Date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
