// <auto-generated />
namespace ViverBemADM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingNewField_Sellers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingNewField_Sellers));
        
        string IMigrationMetadata.Id
        {
            get { return "201601281500028_AddingNewField_Sellers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
